name: learn-github-actions
on: [push]
jobs:
  echo-start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start of Action"
  kotlin-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vroy/gha-kotlin-linter@v3
  echo-end:
    runs-on: ubuntu-latest
    steps:
      - run:  echo "End of Action"
  print-with-script:
    runs-on: ubuntu-latest
    steps:
      - name: Just printing something
        run: .github/scripts/print.sh
        shell: bash
#  example-job-upload:
#    runs-on: ubuntu-latest
#    name: Save output
#    steps:
#      - shell: bash
#        run: |
#          expr i + 1  > output.log
#      - name: Upload output file
#        uses: actions/upload-artifact@v2
#        with:
#          name: output-log-file
#          path: output.log
#  example-job-download:
#    runs-on: ubuntu-latest
#    name: Download output
#    steps:
#      - name: Download a single artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: output-log-file
#      - shell: bash
#        run: |
#          cat output-log-file
