name: Learn Github Actions
on: [push]
jobs:
  echo-start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start of Action"
  kotlin-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vroy/gha-kotlin-linter@v3
  echo-end:
    runs-on: ubuntu-latest
    steps:
      - run:  echo "End of Action"
  print-with-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Just printing something
        run: ./.github/scripts/print.sh
        shell: bash
  example-job-upload:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p test-upload
      - run: echo "Test file uploaded with success!" > test-upload/output.test
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: my-test-upload
          path: test-upload/output.test
  example-job-download:
    runs-on: ubuntu-latest
    name: Download output
    steps:
      - uses: actions/checkout@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: my-test-upload
          path: test-upload/output.test
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: test-upload
